### ISSUE TITLE
New Joint Format V3

### ISSUE THREAD

**Issue by arroyoDev** [ArroyoDev-LLC/3dframe#14]
Upgrades include

Update joint wall thickness froom 2.6 to 4 | https://github.com/ArroyoDev-LLC/3dframe/issues/27
-- | --
Orient all joints and add built in permanent Print support | https://github.com/ArroyoDev-LLC/3dframe/issues/29
Re-calculate joints to fit standard 3/4" stick.  My testing found that a 19.65 hole was the perfect snugness | https://github.com/ArroyoDev-LLC/3dframe/issues/16
For joints whose length is less than 3", reduce the length of the the leg accordingly #11 | https://github.com/ArroyoDev-LLC/3dframe/issues/11
Beef up the inner core of joints and make sure wood sinks into the core. | https://github.com/ArroyoDev-LLC/3dframe/issues/8
Just confirm that EVERY leg hole is pricicely 1.5" deep. | https://github.com/ArroyoDev-LLC/3dframe/issues/5
Extend leg length when legs overlap bacause of minimal angle seperation | https://github.com/ArroyoDev-LLC/3dframe/issues/4
Confirm length calculations are accurate | https://github.com/ArroyoDev-LLC/3dframe/issues/13
Generate End Caps | https://github.com/ArroyoDev-LLC/3dframe/issues/7
Fine Tune updates to labels | https://github.com/ArroyoDev-LLC/3dframe/issues/28

- [ ] only print a single Joint number (ID) like "18" somewhere on the surface where it wont get ruined by support 
- [ ] Joints will have a sticker wrapped on one leg where all 4 faces will boldly display its Letter ID (ex.   "AA"). 
- [ ] Joint legs will have new #7 Lip Caps for Strength.  On these caps will either be printed or sticker wrapped with the target + distance in print on All 4 sides.
- [ ] The Leg Caps will also have 1 off the 4 sides a special color indicating that it and its mate with the special color should face the same direction.  This will ensure orienting the next joint properly for faster assembly.
- [ ] Leg Caps will be rounded to be easier on your hands during assembly.
- [ ] Join sticks will be grooved with the exact depth so that 1.  the user will know when it is deep enough, and 2 will potentially now enjoy a new #2 Gripper feature where it will snap and hold in place.
- [ ] Joint sticks will be painted Silver or grey to look cooler 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/699333/110269586-b0e55a00-7f89-11eb-86ea-f49607cb18b1.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/699333/112665629-45283b80-8e29-11eb-9c4d-a1efcccfc921.png">

**Comment by BradenM** [comment]
Closing b/c (almost) all tasks here are completed.

Think we ended up deciding against #7?
