### ISSUE TITLE
Stick Upgrades

### ISSUE THREAD

**Issue by arroyoDev** [ArroyoDev-LLC/3dframe#3]
Next time:  

- [ ] notch each end of stick as depth guide and for the gripper to grab.   
- [ ] Also Sand pieces and round edges.
- [ ] Paint Silver  
- [ ] Label all 4 sides with length.  
- [ ] Make Length rounded to nearest 10th on cut sheet.

**Comment by BradenM** [comment]
Think most of these are already covered in other issues or no longer valid.
