### ISSUE TITLE
Exact Dimensions Upgrade

### ISSUE THREAD

**Issue by arroyoDev** [ArroyoDev-LLC/3dframe#6]
The first build resulted in a 76% size truck, not 100.  Something went wrong in the conversation process.   The Blender model appears to have the correct dimensions.

The Full Size real truck is"
  Length:  231.7".  (19' 4")
  Width:  79.8".    (6'  7")
  Height:  75".   (6' 2")*.   Air suspension can go as low as 8" and as high as 16" so height can vary.

- [ ] The main goal here is just some way to confirm the size of the model being produced.

This is a small of the length differences between blender and the cut sheet used to build the model
<img width="256" alt="image" src="https://user-images.githubusercontent.com/699333/110257047-95feef80-7f61-11eb-8395-812e254d508a.png">

- [ ] Confirm some dimensions between cut sheet and blender model
- [ ] Next Cut sheet go ahead and round lengths to 1 decimal point (##.#).

**Comment by BradenM** [comment]
Closing this for now as it's impossible to tell if this is still an issue given the vast changes since this was opened.
Cut sheet info is covered in #13
