### ISSUE TITLE
Thicker Base

### ISSUE THREAD

**Issue by arroyoDev** [ArroyoDev-LLC/3dframe#8]
When a leg of a joint is printed in layers going up where its weak-point is to just snap at its base.  We should thicken the base where it intersects with other joints.  If possible we should avoid interrupting a good mounting surface too the print bed.  

The structural flaw is that the fulcrum of peak torque is exactly at the base of the leg.   By submersing the stick inside the core, the fulcrum is now embedded by a great deal more plastic and therefore dramatically increasing strength.  

- [ ] Goal:  surround the incoming dowel into more material (see sketch below)

Here is an example of a joint fail because the leg was printed on the horizontal and could not withstand the stress it had so snapped its base.  
![image](https://user-images.githubusercontent.com/699333/110257494-d5c6d680-7f63-11eb-8d78-df7ed2597680.png)

The idea potentially is simply to taper the base as the joints converge.   
![image](https://user-images.githubusercontent.com/699333/110257644-6ef5ed00-7f64-11eb-9c2b-d3cc3e02f978.png)

Example:  
<img width="895" alt="image" src="https://user-images.githubusercontent.com/699333/119218006-8e041580-baa3-11eb-95b5-c4298dada9d3.png">

**Comment by arroyoDev** [comment]
I now see the new material surrounding the base,  this is great.  however, the stick depth is still at the top of the pyramid, and therefore the fulcrum of any tension is at the weakest point where the walls are still thin.   the goal is to bury the stick inside the new pyramid you create so that the fulcrum is surrounded by more material.   
![IMG_7769](https://user-images.githubusercontent.com/699333/123444433-7fc28100-d59c-11eb-8846-bed1b0fd7954.jpg)
- [ ] ensure the sticks are burred below the new thicker base material

**Comment by BradenM** [comment]
Have added a larger core + chamfered the joint-sided edges:
![image](https://user-images.githubusercontent.com/5913808/125151440-c15e3a80-e10b-11eb-83f8-e878a385baf5.png)

![image](https://user-images.githubusercontent.com/5913808/125151459-e0f56300-e10b-11eb-97db-e7c1f295a53b.png)


This is definitely an improvement, but still not ideal. In the future, I want to implement interior fillets joining the core to each fixture.

See example:

![image](https://raw.githubusercontent.com/wiki/revarbat/BOSL2/images/shapes/interior_fillet.png)
